//! Errors returned by conversions generated by `better_enums`.

/// An integer value that cannot be converted to a generated enum or bitflags
/// value.
///
/// `Discriminant` is returned when a range-based enum has no variant mapped to
/// the input value. `Bit` is returned when a bitflags value contains a bit that
/// is not declared by the enum.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum BetterEnumsError<T> {
    /// The value is not mapped to any enum variant.
    Discriminant(T),
    /// The value contains a bit not represented by the bitflag enum.
    Bit(T),
}

impl<T: std::fmt::Display> std::fmt::Display for BetterEnumsError<T> {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Bit(t) => write!(formatter, "{} contains an invalid bit", t),
            Self::Discriminant(t) => write!(formatter, "{} is not a valid discriminant", t),
        }
    }
}

impl<T: std::fmt::Debug + std::fmt::Display> std::error::Error for BetterEnumsError<T> {}
