//! Bitflag support for enums generated with the `better_enums` attribute.
//!
//! Add `#[better_enums(bitflags)]` to an enum whose variants each represent one
//! non-zero power-of-two bit. The generated implementations let you combine
//! variants with `|` and produce a [`Bitflags`] value:
//!
//! ```
//! use better_enums::{better_enums, flags::TryFromBits};
//!
//! #[better_enums(bitflags)]
//! #[repr(u8)]
//! enum Permission {
//!     Read = 0b0001,
//!     Write = 0b0010,
//!     Execute = 0b0100,
//! }
//!
//! let permissions = Permission::Read | Permission::Write;
//! assert!(permissions.contains(Permission::Read));
//! assert_eq!(permissions.value(), 0b0011);
//! assert!(Permission::try_from_bits(0b1000).is_err());
//! ```
//!
//! Use [`TryFromBits`] for non-exhaustive enums, where some representation bits
//! are not declared. If the enum declares every bit, the macro also implements
//! [`FromBits`], which provides an infallible conversion.

use std::ops::{
    BitAnd, BitAndAssign, BitOr, BitOrAssign, BitXor, BitXorAssign, Not, Shl, ShlAssign, Shr,
    ShrAssign,
};

use crate::error::BetterEnumsError;

pub use traits::*;

macro_rules! for_each_number_primitive {
    ($d:tt $name:ident => $($code:tt)*) => {
        macro_rules! implement {
            ($d $name:ty) => {
                $($code)*
            };
        }

        implement!(u8);
        implement!(u16);
        implement!(u32);
        implement!(u64);
        implement!(u128);
        implement!(usize);
        implement!(i8);
        implement!(i16);
        implement!(i32);
        implement!(i64);
        implement!(i128);
        implement!(isize);
    };
}

mod traits {

    use super::*;

    #[doc(hidden)]
    /// Internal trait implemented by bitflag enums generated by the macro.
    ///
    /// This trait is not intended to be implemented by users. Use
    /// [`Bitflags`] and the conversion traits instead.
    pub trait Bit: Sized {
        type Repr: Copy
            + Clone
            + Sized
            + BitAnd<Self::Repr, Output = Self::Repr>
            + BitOr<Self::Repr, Output = Self::Repr>
            + BitXor<Self::Repr, Output = Self::Repr>
            + Shl<u8, Output = Self::Repr>
            + Shl<u16, Output = Self::Repr>
            + Shl<u32, Output = Self::Repr>
            + Shl<u64, Output = Self::Repr>
            + Shl<u128, Output = Self::Repr>
            + Shl<usize, Output = Self::Repr>
            + Shl<i8, Output = Self::Repr>
            + Shl<i16, Output = Self::Repr>
            + Shl<i32, Output = Self::Repr>
            + Shl<i64, Output = Self::Repr>
            + Shl<i128, Output = Self::Repr>
            + Shl<isize, Output = Self::Repr>
            + Shr<u8, Output = Self::Repr>
            + Shr<u16, Output = Self::Repr>
            + Shr<u32, Output = Self::Repr>
            + Shr<u64, Output = Self::Repr>
            + Shr<u128, Output = Self::Repr>
            + Shr<usize, Output = Self::Repr>
            + Shr<i8, Output = Self::Repr>
            + Shr<i16, Output = Self::Repr>
            + Shr<i32, Output = Self::Repr>
            + Shr<i64, Output = Self::Repr>
            + Shr<i128, Output = Self::Repr>
            + Shr<isize, Output = Self::Repr>
            + Not<Output = Self::Repr>
            + PartialEq
            + Eq
            + PartialOrd
            + Ord
            + 'static;

        /// The value of all enum variants combined.
        const FULL: Self::Repr;
        /// The value of no enum variants combined.
        const EMPTY: Self::Repr;

        /// Returns the underlying value of the enum variant.
        fn value(&self) -> Self::Repr;

        /// Returns an empty set of flags.
        #[inline(always)]
        fn empty() -> Bitflags<Self> {
            Bitflags(Self::EMPTY)
        }

        /// Returns a set of flags with all possible flags set.
        #[inline(always)]
        fn full() -> Bitflags<Self> {
            Bitflags(Self::FULL)
        }
    }

    #[doc(hidden)]
    /// Internal marker for enums that define every bit in their representation.
    ///
    /// This trait is implemented by the macro when `FULL` contains every bit
    /// of the enum's unsigned representation. It enables [`FromBits`] and
    /// operations such as `!` and shifts that are only safe for exhaustive
    /// flags. It is not intended to be implemented by users.
    pub trait ExhaustiveBit: Bit {}

    /// Converts a complete integer representation into [`Bitflags`] without
    /// returning a `Result`.
    ///
    /// This trait is available only for exhaustive bitflag enums: every bit in
    /// the representation is declared by a variant, so every representation
    /// value is valid. For non-exhaustive enums, use [`TryFromBits`].
    pub trait FromBits: Sized + ExhaustiveBit {
        /// Converts the underlying representation into a set of flags.
        #[must_use]
        fn from_bits(value: Self::Repr) -> Bitflags<Self>;
    }

    /// Fallibly converts an integer representation into [`Bitflags`].
    ///
    /// Use this trait for non-exhaustive bitflag enums. The conversion rejects
    /// values containing bits that are not represented by an enum variant and
    /// returns [`BetterEnumsError::Bit`](crate::error::BetterEnumsError::Bit).
    /// For exhaustive enums, [`FromBits`] provides an infallible conversion.
    pub trait TryFromBits: Sized + Bit {
        /// The type returned in the event of a conversion error.
        type Error;

        /// Performs the conversion.
        fn try_from_bits(value: Self::Repr) -> Result<Bitflags<Self>, Self::Error>;
    }
}

/// A set of combined flags for a bitflag enum.
///
/// `Bitflags<T>` is created by combining enum variants with bitwise operators,
/// or by converting an integer with [`FromBits::from_bits`] or
/// [`TryFromBits::try_from_bits`]. It stores the combined underlying integer
/// value and can be queried with [`contains`](Self::contains),
/// [`is_empty`](Self::is_empty), [`is_full`](Self::is_full), and
/// [`value`](Self::value).
///
/// Bitwise operations are supported between two `Bitflags` values and between
/// a `Bitflags` value and an individual enum variant. Complement and shift
/// operations are available only for exhaustive bitflag enums.
#[derive(Debug, Clone, Copy, PartialEq, PartialOrd, Eq, Ord)]
pub struct Bitflags<T: Bit>(T::Repr);

impl<T: Bit> Bitflags<T> {
    /// Returns whether all bits in `flag` are set.
    #[inline(always)]
    pub fn contains(&self, flag: T) -> bool {
        self.0 & flag.value() == flag.value()
    }

    /// Returns whether no flags are set.
    #[inline(always)]
    pub fn is_empty(&self) -> bool {
        self.0 == T::EMPTY
    }

    /// Returns whether all flags declared by the enum are set.
    #[inline(always)]
    pub fn is_full(&self) -> bool {
        self.0 == T::FULL
    }

    /// Returns the underlying integer value of the combined flags.
    #[inline(always)]
    pub fn value(&self) -> T::Repr {
        self.0
    }
}

impl<T: ExhaustiveBit> FromBits for T {
    fn from_bits(value: Self::Repr) -> Bitflags<Self> {
        if T::FULL & value == value {
            Bitflags(value)
        } else {
            unreachable!("better_enums: ExhaustiveBit implementation for non-exhaustive enum")
        }
    }
}

impl<T: Bit> TryFromBits for T {
    type Error = BetterEnumsError<T::Repr>;

    fn try_from_bits(value: Self::Repr) -> Result<Bitflags<Self>, Self::Error> {
        if T::FULL & value == value {
            Ok(Bitflags(value))
        } else {
            Err(BetterEnumsError::Bit(value))
        }
    }
}

impl<T: Bit> BitAnd<T> for Bitflags<T> {
    type Output = Self;
    #[inline(always)]
    fn bitand(self, rhs: T) -> Self::Output {
        Self(self.0.bitand(rhs.value()))
    }
}

impl<T: Bit> BitOr<T> for Bitflags<T> {
    type Output = Self;
    #[inline(always)]
    fn bitor(self, rhs: T) -> Self::Output {
        Self(self.0.bitor(rhs.value()))
    }
}

impl<T: Bit> BitXor<T> for Bitflags<T> {
    type Output = Self;
    #[inline(always)]
    fn bitxor(self, rhs: T) -> Self::Output {
        Self(self.0.bitxor(rhs.value()))
    }
}

impl<T: Bit> BitAndAssign<T> for Bitflags<T> {
    #[inline(always)]
    fn bitand_assign(&mut self, rhs: T) {
        self.0 = self.0.bitand(rhs.value());
    }
}

impl<T: Bit> BitOrAssign<T> for Bitflags<T> {
    #[inline(always)]
    fn bitor_assign(&mut self, rhs: T) {
        self.0 = self.0.bitor(rhs.value());
    }
}

impl<T: Bit> BitXorAssign<T> for Bitflags<T> {
    #[inline(always)]
    fn bitxor_assign(&mut self, rhs: T) {
        self.0 = self.0.bitxor(rhs.value());
    }
}

impl<T: ExhaustiveBit> Not for Bitflags<T> {
    type Output = Self;
    #[inline(always)]
    fn not(self) -> Self::Output {
        Self(self.0.not())
    }
}

impl<T: Bit> BitAnd for Bitflags<T> {
    type Output = Self;
    #[inline(always)]
    fn bitand(self, rhs: Self) -> Self::Output {
        Self(self.0.bitand(rhs.value()))
    }
}

impl<T: Bit> BitOr for Bitflags<T> {
    type Output = Self;
    #[inline(always)]
    fn bitor(self, rhs: Self) -> Self::Output {
        Self(self.0.bitor(rhs.value()))
    }
}

impl<T: Bit> BitXor for Bitflags<T> {
    type Output = Self;
    #[inline(always)]
    fn bitxor(self, rhs: Self) -> Self::Output {
        Self(self.0.bitxor(rhs.value()))
    }
}

impl<T: Bit> BitAndAssign for Bitflags<T> {
    #[inline(always)]
    fn bitand_assign(&mut self, rhs: Self) {
        self.0 = self.0.bitand(rhs.value());
    }
}

impl<T: Bit> BitOrAssign for Bitflags<T> {
    #[inline(always)]
    fn bitor_assign(&mut self, rhs: Self) {
        self.0 = self.0.bitor(rhs.value());
    }
}

impl<T: Bit> BitXorAssign for Bitflags<T> {
    #[inline(always)]
    fn bitxor_assign(&mut self, rhs: Self) {
        self.0 = self.0.bitxor(rhs.value());
    }
}

for_each_number_primitive!($type =>
    impl<T: ExhaustiveBit> Shr<$type> for Bitflags<T> {
        type Output = Self;
        #[inline(always)]
        fn shr(self, rhs: $type) -> Self::Output {
            Self(self.0.shr(rhs))
        }
    }

    impl<T: ExhaustiveBit> Shl<$type> for Bitflags<T> {
        type Output = Self;
        #[inline(always)]
        fn shl(self, rhs: $type) -> Self::Output {
            Self(self.0.shl(rhs))
        }
    }

    impl<T: ExhaustiveBit> ShrAssign<$type> for Bitflags<T> {
        #[inline(always)]
        fn shr_assign(&mut self, rhs: $type) {
            self.0 = self.0.shr(rhs);
        }
    }

    impl<T: ExhaustiveBit> ShlAssign<$type> for Bitflags<T> {
        #[inline(always)]
        fn shl_assign(&mut self, rhs: $type) {
            self.0 = self.0.shl(rhs);
        }
    }
);
